<a href="https://colab.research.google.com/github/sidneyhendrzak/avalanche-analysis-mod-2k/blob/main/AvalancheAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Avalanche Analysis of Linear Congruential Mappings

This notebook analyzes the avalanche effect and Strict Avalanche Criterion (SAC) for functions of the form y = (a * x + b) mod 2^k, by exhaustively flipping input bits and measuring how output bits change. [file:45]


## Method Summary

- For a given bit-length k, consider all inputs x in {0, …, 2^k - 1}. [file:45]
- For each input bit i, flip that bit and compare y = (a * x + b) mod 2^k to y_flipped. [file:45]
- Count how often each output bit changes, build SAC matrices (rows = output bits, cols = input bits). [file:45]
- Compute average number of bits changed per input flip to assess avalanche behavior. [file:45]


In [1]:
import numpy as np

def int_to_bits(x, k):
    return np.array([int(b) for b in f"{x:0{k}b}"])

def avalanche_analysis(k):
    N = 2 ** k
    a_values = [a for a in range(3, N, 2)]
    b_values = range(N)
    for a in a_values:
        for b in b_values:
            total_flips = 0
            total_bits_changed = 0
            sac_matrix = np.zeros((k, k))
            for x in range(N):
                for i in range(k):
                    x_flipped = x ^ (1 << i)
                    y = (a * x + b) % N
                    y_flipped = (a * x_flipped + b) % N
                    y_bits = int_to_bits(y, k)
                    y_flipped_bits = int_to_bits(y_flipped, k)
                    diff = y_bits ^ y_flipped_bits
                    bits_changed = np.sum(diff)
                    total_bits_changed += bits_changed
                    total_flips += 1
                    for j in range(k):
                        if diff[j]:
                            sac_matrix[j, i] += 1
            avg_bits_changed = total_bits_changed / total_flips
            sac_props = sac_matrix / N
            print(f"a={a}, b={b}, avg_bits_changed={avg_bits_changed:.3f}")
            print("SAC matrix (rows=output bits, cols=input bits):")
            print(np.round(sac_props, 3))
            print()

print("=== Avalanche Analysis for k=3 ===")
avalanche_analysis(3)

print("=== Avalanche Analysis for k=4 ===")
avalanche_analysis(4)


=== Avalanche Analysis for k=3 ===
a=3, b=0, avg_bits_changed=1.667
SAC matrix (rows=output bits, cols=input bits):
[[0.5 0.5 1. ]
 [1.  1.  0. ]
 [1.  0.  0. ]]

a=3, b=1, avg_bits_changed=1.667
SAC matrix (rows=output bits, cols=input bits):
[[1. 1. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

a=3, b=2, avg_bits_changed=1.667
SAC matrix (rows=output bits, cols=input bits):
[[0.5 0.5 1. ]
 [1.  1.  0. ]
 [1.  0.  0. ]]

a=3, b=3, avg_bits_changed=1.333
SAC matrix (rows=output bits, cols=input bits):
[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

a=3, b=4, avg_bits_changed=1.667
SAC matrix (rows=output bits, cols=input bits):
[[0.5 0.5 1. ]
 [1.  1.  0. ]
 [1.  0.  0. ]]

a=3, b=5, avg_bits_changed=1.667
SAC matrix (rows=output bits, cols=input bits):
[[1. 1. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

a=3, b=6, avg_bits_changed=1.667
SAC matrix (rows=output bits, cols=input bits):
[[0.5 0.5 1. ]
 [1.  1.  0. ]
 [1.  0.  0. ]]

a=3, b=7, avg_bits_changed=1.333
SAC matrix (rows=output bits, cols=input bits):
[[1. 0. 1.]
 [0